[package]
name = "monte"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# TODO: add a bunch of opt-in features that keep compile time low

[dependencies]
