[build-system]
requires = ["maturin>=0.14,<0.15"]
build-backend = "maturin"

[project]
name = "monte"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Rust",
]


[tool.maturin]
features = ["pyo3/extension-module"]
